language: python
python:
  - 2.7
install:
  - pip install --upgrade setuptools
  - ls -lha /home/travis/virtualenv/python2.7/lib/python2.7/site-packages/
  - python bootstrap.py
  - bin/buildout
script:
  - bin/test
